<?php
/**
 * Product list toolbar amount - Custom Design
 * @var \Magento\Catalog\Block\Product\ProductList\Toolbar $block
 * @var \Magento\Framework\Locale\LocaleFormatter $localeFormatter
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<p class="product-count-text">
    <?php if ($block->getLastPageNum() > 1):?>
        <?= $escaper->escapeHtml(
            __(
                'Showing %1-%2 of %3 products',
                '<span class="count-number">' . $localeFormatter->formatNumber($block->getFirstNum()) . '</span>',
                '<span class="count-number">' . $localeFormatter->formatNumber($block->getLastNum()) . '</span>',
                '<span class="count-number">' . $localeFormatter->formatNumber($block->getTotalNum()) . '</span>'
            ),
            ['span']
        ) ?>
    <?php elseif ($block->getTotalNum() == 1):?>
        <?= $escaper->escapeHtml(
            __(
                'Showing %1 product',
                '<span class="count-number">' . $localeFormatter->formatNumber($block->getTotalNum()) . '</span>'
            ),
            ['span']
        ) ?>
    <?php else:?>
        <?= $escaper->escapeHtml(
            __(
                'Showing %1 products',
                '<span class="count-number">' . $localeFormatter->formatNumber($block->getTotalNum()) . '</span>'
            ),
            ['span']
        ) ?>
    <?php endif; ?>
</p>




