<?php
/**
 * Product list toolbar amount - Custom Design
 * @var \Magento\Catalog\Block\Product\ProductList\Toolbar $block
 * @var \Magento\Framework\Locale\LocaleFormatter $localeFormatter
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<p class="product-count-text">
    <?php if ($block->getLastPageNum() > 1):?>
        <?= $escaper->escapeHtml(
            __(
                'Showing <span class="count-number">%1</span> products',
                $localeFormatter->formatNumber($block->getTotalNum())
            ),
            ['span']
        ) ?>
    <?php elseif ($block->getTotalNum() == 1):?>
        <?= $escaper->escapeHtml(
            __(
                'Showing <span class="count-number">%1</span> product',
                $localeFormatter->formatNumber($block->getTotalNum())
            ),
            ['span']
        ) ?>
    <?php else:?>
        <?= $escaper->escapeHtml(
            __(
                'Showing <span class="count-number">%1</span> products',
                $localeFormatter->formatNumber($block->getTotalNum())
            ),
            ['span']
        ) ?>
    <?php endif; ?>
</p>




