<?php
/**
 * Product list toolbar sorter - Custom Design
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div class="sort-wrapper">
    <label class="sort-label" for="sorter"><?= $escaper->escapeHtml(__('Sort By')) ?></label>
    <select id="sorter" data-role="sorter" class="sort-select">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
            <option value="<?= $escaper->escapeHtmlAttr($_key) ?>"
                <?php if ($block->isOrderCurrent($_key)) :?>
                    selected="selected"
                <?php endif; ?>
                >
                <?= $escaper->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>




